**Run the following two cells before you begin.**

In [3]:
%autosave 10

Autosaving every 10 seconds


In [4]:
import pandas as pd
import numpy as np

______________________________________________________________________
**First, import your data set and define the sigmoid function.**
<details>
    <summary>Hint:</summary>
    The definition of the sigmoid is $f(x) = \frac{1}{1 + e^{-X}}$.
</details>

In [5]:
# Import the data set
data = pd.read_csv('cleaned_data.csv')

In [33]:
data.shape[0]

26664

In [6]:
# Define the sigmoid function
X_exp = np.linspace(-4,4,81)
print(X_exp[:5])
print(X_exp[-5:])

[-4.  -3.9 -3.8 -3.7 -3.6]
[3.6 3.7 3.8 3.9 4. ]


In [84]:
#sigmoid function 
y_exp = 1/(1 + np.exp(-X_exp))
y_exp

array([0.01798621, 0.01984031, 0.02188127, 0.02412702, 0.02659699,
       0.02931223, 0.03229546, 0.03557119, 0.03916572, 0.04310725,
       0.04742587, 0.05215356, 0.05732418, 0.06297336, 0.06913842,
       0.07585818, 0.0831727 , 0.09112296, 0.09975049, 0.10909682,
       0.11920292, 0.13010847, 0.14185106, 0.15446527, 0.16798161,
       0.18242552, 0.19781611, 0.21416502, 0.23147522, 0.24973989,
       0.26894142, 0.2890505 , 0.31002552, 0.33181223, 0.35434369,
       0.37754067, 0.40131234, 0.42555748, 0.450166  , 0.47502081,
       0.5       , 0.52497919, 0.549834  , 0.57444252, 0.59868766,
       0.62245933, 0.64565631, 0.66818777, 0.68997448, 0.7109495 ,
       0.73105858, 0.75026011, 0.76852478, 0.78583498, 0.80218389,
       0.81757448, 0.83201839, 0.84553473, 0.85814894, 0.86989153,
       0.88079708, 0.89090318, 0.90024951, 0.90887704, 0.9168273 ,
       0.92414182, 0.93086158, 0.93702664, 0.94267582, 0.94784644,
       0.95257413, 0.95689275, 0.96083428, 0.96442881, 0.96770

**Now, create a train/test split (80/20) with `PAY_1` and `LIMIT_BAL` as features and `default payment next month` as values. Use a random state of 24.**

In [47]:
X1 = data.iloc[:,[6,1]] 
X1.shape

(26664, 2)

In [9]:
Y = data['default payment next month']
Y1 = Y.values
Y1

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [10]:
# Create a train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1,Y1, test_size=0.2, random_state=24) 

______________________________________________________________________
**Next, import LogisticRegression, with the default options, but set the solver to `'liblinear'`.**

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression 

In [12]:
model = LogisticRegression(solver='liblinear')

______________________________________________________________________
**Now, train on the training data and obtain predicted classes, as well as class probabilities, using the testing data.**

In [13]:
# Fit the logistic regression model on training data
model.fit(X_train, y_train) 

LogisticRegression(solver='liblinear')

In [88]:
# Make predictions using `.predict()`
y_pred = model.predict(X_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [89]:
# Find class probabilities using `.predict_proba()`
y_pred_proba = model.predict_proba(X_test)
y_pred_proba

array([[0.74826924, 0.25173076],
       [0.584297  , 0.415703  ],
       [0.79604453, 0.20395547],
       ...,
       [0.584297  , 0.415703  ],
       [0.82721498, 0.17278502],
       [0.66393435, 0.33606565]])

______________________________________________________________________
**Then, pull out the coefficients and intercept from the trained model and manually calculate predicted probabilities. You'll need to add a column of 1s to your features, to multiply by the intercept.**

In [35]:
m = data.shape[0]
m

26664

In [55]:
X_b = np.c_[np.ones((m,1)), X1] 
X_b

array([[ 1.0e+00,  2.0e+00,  2.0e+04],
       [ 1.0e+00, -1.0e+00,  1.2e+05],
       [ 1.0e+00,  0.0e+00,  9.0e+04],
       ...,
       [ 1.0e+00,  4.0e+00,  3.0e+04],
       [ 1.0e+00,  1.0e+00,  8.0e+04],
       [ 1.0e+00,  0.0e+00,  5.0e+04]])

In [16]:
np.random.seed(seed=6)
X_1_pos = np.random.uniform(low=1, high=7, size=(20,1))
print(X_1_pos[0:3])
X_1_neg = np.random.uniform(low=3, high=10, size=(20,1))
print(X_1_neg[0:3])
X_2_pos = np.random.uniform(low=1, high=7, size=(20,1))
print(X_1_pos[0:3])
X_2_neg = np.random.uniform(low=3, high=10, size=(20,1))
print(X_1_neg[0:3])

[[6.35716091]
 [2.99187883]
 [5.92737474]]
[[3.38132155]
 [8.03046066]
 [8.61519394]]
[[6.35716091]
 [2.99187883]
 [5.92737474]]
[[3.38132155]
 [8.03046066]
 [8.61519394]]


In [17]:
# Add column of 1s to features
y_pred = model.predict(X_test)
positive_indices = [counter for counter in range(len(y_pred)) if y_pred[counter]==1]
negative_indices = [counter for counter in range(len(y_pred)) if y_pred[counter]==0]
positive_indices

[]

In [18]:
import matplotlib.pyplot as plt

In [57]:
# Get coefficients and intercepts from trained model
theta_1 = model.coef_[0][0]
theta_2 = model.coef_[0][1]
theta_3 = model.coef_
print(theta_1, theta_2)

#intercept
theta_0 =  model.intercept_
theta_3

8.274511867131002e-11 -6.808767266629246e-06


array([[ 8.27451187e-11, -6.80876727e-06]])

In [60]:
intercept_coefs = np.concatenate([theta_0.reshape(1,1),theta_3],axis = 1)
intercept_coefs

array([[-6.57647457e-11,  8.27451187e-11, -6.80876727e-06]])

In [63]:
X_1_decision_boundary = np.array([0, 10])
X_2_decision_boundary = -(theta_1/theta_2)*X_1_decision_boundary - (theta_0/theta_2)
X_1_decision_boundary 
 

array([ 0, 10])

In [64]:
X_2_decision_boundary

array([-9.65883296e-06,  1.11868479e-04])

In [66]:
X_prod = np.dot(intercept_coefs,np.transpose(X_b))
X_prod

array([[-0.13617535, -0.81705207, -0.61278905, ..., -0.20426302,
        -0.54470138, -0.34043836]])

In [82]:
def sigmoid(X_exp):
    y_exp = 1/(1 + np.exp(-X_exp))
    return y_exp
  

In [87]:
# predicted probability 
y_pred_proba1 = sigmoid(X_prod) 
y_pred_proba1

array([[0.46600867, 0.30638978, 0.35142324, ..., 0.44911106, 0.3670946 ,
        0.415703  ]])

______________________________________________________________________
**Next, using a threshold of `0.5`, manually calculate predicted classes. Compare this to the class predictions output by scikit-learn.**

In [27]:
# Manually calculate predicted classes
y_pred_mannual = y_pred_proba>=0.5
y_pred_mannual

array([[ True, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [ True, False],
       [ True, False]])

In [28]:
# Compare to scikit-learn's predicted classes
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
y_pred_mannual.shape

(5333, 2)

In [30]:
y_pred.shape

(5333,)

______________________________________________________________________
**Finally, calculate ROC AUC using both scikit-learn's predicted probabilities, and your manually predicted probabilities, and compare.**

In [72]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn import metrics
from sklearn.metrics import auc 

In [75]:
# Use scikit-learn's predicted probabilities to calculate ROC AUC
auc_score1 = roc_auc_score(y_test,y_pred_proba[:,1])
auc_score1

0.627207450280691